### ISSUE TITLE
System needs to allow multiple taxonomies for response organization

### ISSUE THREAD

**Issue by tonysurma** [HTBox/crisischeckin#309]
Currently the system is hardcoded to use the cluster system from the UN.  In implementation in the field domestically and internationally different taxonomies are used to organize response functions.  In order to support however responses are organized the system should be updated to allow for multiple taxonomies to be defined and selected as a response/disaster is initiated.  This will also impact volunteer registration as it currently stands.

Child Issues:
- [ ] #308 Implement interface for Administrator to create taxonomies with a name and list of options within
- [ ] #309 Allow Administrators to edit taxonomy name and list of options (add new, edit name and 'retire' existing options)
- [ ] #310 During disaster creation allow selection of a taxonomy
- [ ] #311 During volunteer registration remove selection of cluster (deferred to checkin)
- [ ] #312 During volunteer checkin volunteer chooses option from disaster's configured taxonomy
- [ ] #313 During volunteer checkin preselect taxonomy choice if volunteer previously checked in to an option in the disasters taxonomy
