### ISSUE TITLE
Mobile App development checklist

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#650]
This issue will layout the general requirements and desired features of the mobile app version of crisis checkin.

 PLEASE read the MobileAppdevelopmentv1.docx found under the folder called "Docs".I have also provided the link to a wireframe model of this app (designed to guide the front end dev).

Each task in the following task list will represent a front end view and a link to a corresponding issue. Each issue will provide details about the front end as well as what it connects to on the back end. 

- [ ] Login Screen(initial page)

- [ ] Registration

- [ ] Profile view(Home screen)

- [ ] Disaster Checkin 

- [ ] Add/view Contacts

- [ ] Add/view Resources

- [ ] Add/view Field Reported data

**Comment by brunck** [comment]
@BillWagner @tonysurma The wireframe link is now bad. Are we still pursuing this flow?
